highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

mode: product
url: https://twainj.github.io/
devurl: http://localhost:4000/
name: TwainJ
title: TwainJ | DevBlog
description: "TwainJ's dev weblog, on tech, particularly code"

sass:
  sass_dir: _sass


my:
    displayName: TwainJ
    realName: "Jason Jones"
    jobTitle: "Developer"
    contact:
        email: jason@2jdevelopment.com
        github: https://github.com/twainj
        stackoverflow: http://stackoverflow.com/users/57001/twainj
        tel: 15416004096
        address:
            city: Prineville
            state: Oregon
            country: USA
    skills:
        frontend: ["HTML | Markdown","JavaScript"]
        backend: ["ASP.NET MVC", "PHP", "Node.js"]
        tools: ["Visual Studio", "Git", "Linux"]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
